= DW

== Tag 1.12.2020

* Ich wünsche mir so sehr, dass es in diesem Winter schneit. - I wish so much that it snows this winter.

* Ich komme aus der Schweiz. Und du? - I come from Switzerland. And you?

* Können wir in deiner Mittagspauze kurz sprechen? - Can we talk briefly during your lunch break?

== Tag 30 November 2020

* Meinst du, ich soll wirklich bei diesem Unternehmen bewerben? - Do you think I should really apply to this company?

* Wie geht's dir heute? Schon etwas besser danke. - How are you today? Already a little better thanks.

* Geduld ist nicht unbedingt eine meiner Stärken - Patience is not necessarily one of my strengths.

* Ich vermisse dich! - I miss you

* Meine Mutter kocht immer etwas für mich, wenn ich aus der Schule komme.

* Marrie mag keinen Kaffee.

== Tag 28 November 2020

* Henriette liebt das Buch, das sie von ihrer Mutter geschenkt bekommen hat. - Henriette loves the book that her mother gave her.

* Sie liebt ihn gar nicht, sodern ist nur auf sein Geld aus! - She doesn't love him at all, but is only after his money!

* Ich bin am liebsten draußen, wenn die Sonne scheint. - I prefer to be outside when the sun is shining.

* Kannst du das bitte noch einmal widerholen? Er ist so laut hier. - Can you please repeat that again? He's so loud here.

* Ich kann es kaum erwarten, bald wieder zu Hause zu sein! - I can not wait, soon to be home again!

* Hast du schon die Rechnung bezahlt? - Have you paid the bill yet?


== Tag 27.11.2020

* Ich muss mich beeilen, weil ich heute pünktlich gehen will - I have to hurry because I want to leave on time today

* Ich gehe gerne zu Fuß - I like to walk

* Ich finde die Argumente des Politikers überzeugt - I find the politician's arguments convincing

* Im Schnitt mache ich zwei bis dreimal die Woche Sport. - On average, I do sport two to three times a week.

* Darfst du einfach so früh Feierabend machen? -  Can you just quit work so early?

* Jetzt hilf mir doch mal! - Now help me out!




* Marie mag keinen Kaffee.

* Das schaffe ich mit links - I can do that with my left hand

* Ich glaube, der Laden ist heute geschlossen - I think the store is closed today.

* Durch die Klimaerwärmung steht die Zukunft useres Planeten auf dem Spiel - The future of our planet is at stake due to global warning.
* Kannst du die Flasche auf den Tisch da vorne stellen - Can you put the bottle on the table over there

* Nächste Woche habe ich sehr viel zu tun. Deswegen kann ich noch nicht sagen, ob ich es schaffe, dich zu treffen. - I will be very busy next week. That is why I can not say wheather I will be able to meet you.

* Ich mag es gar nicht, wenn du traurig bist. - I do not like it when you are sad.

---------------------


