= DW

== Tag 22.12.2020
* Ich habe am Wochenende Plätzchen für die ganze Familie gebacken. - I baked cookies for the whole family on the weekend.
* Das Klavier muss dringend wieder gestimmt werden - The piano urgently needs to be tuned again

== Tag 21.12.2020

* Hey, das ist meine Zeitschrift! Kauf dir doch eine eigene. - Hey this is my magazine! Buy your own
* Darf ich Ihnen dieses Gericht hier empfehlen? Es schmeckt wirklich gut. - May I recommend this dish to you? It tastes really good.
* Du schaust schon den ganzen Tag Fernsehen. Kannst du das Ding nicht mal ausmachen? - You've been watching TV all day. Can't you even turn that thing off?
* Was wäre dir lieber, Früh- oder Spätschicht?
* Ich habe so viel zu erledigen. Ich bin komplett überfordert. - I have so much to do. I am completely overwhelmed.

== Tag 20.12.2020

* Was wollen wir heute machen? Ein Ausflug wäre toll, finde ich. - What do we want to do today? I think a trip would be great.
* Ich habe dir doch schon oft gesagt, dass du mich um Hilfe bitten kannst. - I have told you many times that you can ask me for help.
* Was hättest du lieber? Kaffee oder Tee? - What would you rather have? Coffee or tea?
* Es ist ganz schön unordentlich hier. Du solltest doch dein Zimmer aufräumen. - It's pretty messy here. You should clean up your room.
* Ich muss dringend meine Pflanze umtopfen. Sie hat kaum noch Platz in ihrem Topf. - I urgently need to repot my plant. There is hardly any space left in her pot.
* Das ist das Gesetz, das das alte ersetzt. Gut, dass es reformiert wurde! - This is the law that replaces the old one. Good thing it was reformed!

== Tag 19.12.2020
* Mein Handy kann gerade keine Verbindung aufbauen. - My cell phone cannot establish a connection at the moment.
* Immer wenn wir an der Garderobe anstehen, drängelt sich jemand vor - Whenever we queue in the cloakroom, someone pushes ahead
* Ob ich wohl morgen früher von der Arbeit nach Hause gehen darf? - Can I go home from work earlier tomorrow?
* Entschuldigung, hätten Sie kurz Zeit für mich? - Excuse me, would you have a minute to see me?
* Anja wohnt ziemlich weit außerhalb Kölns. - Anja lives a long way outside of Cologne.
* Ute läuft jeden Morgen durch den Park zur Bahnhaltestelle. - Every morning Ute walks through the park to the train station.
* Welche Bedeutung nimmt dieses Wort? - What is the meaning of this word?




== Tag 6.12.2020

* Ich werde ein Praktikum in Berlin machen und suche für die Zeit noch eine Bleibe. - I'll do an internship in Berlin and look for somewhere to stay around that time.
* Ich habe im Moment keine Zeit dazu, Sport zu machen. - I don't have time to exercise right now.
* Wenn ich mehr Zeit hätte, würde ich mehr Sport treiben. - If I had more time, I would do more sports.
* Ich gehe ihm die Schuld an dem Unfall. - I blame him for the accident
* Hast du Einfluss auf diese Entscheidung. - Do you have an influence on this decision?
* Freust du dich auch schon so sehr auf Weihnachten wie ich? - Are you looking forward to Christmas as much as I am?

== Tag 5.12.2020

* Der Reporter hat über das Geschehen Bericht erstattet. - The reporter reported on what happened.
* Die Erzählungen über seine Weltreise haben meine Neugier geweckt. - The stories about his trip around the world have aroused my curiosity.
* Lebt deine Urgroßmutter wtwa noch ? Nein, sie lebt nicht mehr - Is your great grandmother wtwa still alive? No, she is no longer alive
* Wann hast du denn das letzte Mal Urlaub gemacht? - When was the last time you went on vacation?
* Ich habe mir vorgenommen zwei Wochen auf Zucker zu verzichten. - I have decided to go without sugar for two weeks.
* Er stand seiner Familie in dieser schweren Stunde bei. - He stood by his family in this difficult hour.
* Vor dem Umzug muss ich noch viele Sachen aussortieren. - Before moving, I have to sort out a lot of things.

== Tag 4.12.2020

* Wo warst du so lange? Ich komme gerade von der Uni. - Where have you been so long? I have just come from university.
* Der Film handelt über einem Paar, das heiraten möchte. - The film is about a couple who want to get married.
* Können Sie bitte noch dies Formular ausfüllen? - Can you please fill out this form?
* Ich bin total begeistert von dieser neuen Diät. Ich habe schon zwei Kilo abgenommen. - I am absolutely thrilled with this new diet. I've already lost two pounds.
* Das Unternehmen hat Insolvenz angemeldet. - The company has filed for bankruptcy.
* Musst du heute noch viel erledigen? - Do you still have a lot to do today?

== Tag 3.12.2020

* Entschuldigung, was kostet das?
* Wir überspringen Übung Nummer 2.
* Hast du Lust, dich morgen früh zum Frühstück zu treffen? - Would you like to meet up for breakfast tomorrow morning?
* Wo findet das heutige Meeting statt ? - Where is today's meeting taking place?
* Ich möchte mich für einen Kurs anmelden. - I want to register for a course.
* Mach sofort die Zigarette aus. Hier darf  man nicht rauchen. - Put out the cigarette immediately. It is not allowed to smoke here.
* Mama hat gesagt, du sollst mir beim Aufräumen helfen! - Mama said you should help me clean up!

== Tag 2.12.2020

* Heute ist ein schöner tag! - Today is a nice day!

* Die beiden haben gerade eine kleine Krise. Hoffentlich wird es bald wieder besser. - The two are in a little crisis. Hopefully it will get better soon.

* Wollen wir uns heute Abend um 19 Uhr treffen?

* Es tut mir leid. Kannst du mir jemals vergeben? - I'm so sorry. Can you ever forgive me

* Als kind wollte ich immer eine Lehrerin werden.

* Kannst du mir noch eben helfen, den Tisch abräumen. - Can you help me clear the table?

== Tag 1.12.2020

* Ich wünsche mir so sehr, dass es in diesem Winter schneit. - I wish so much that it snows this winter.

* Ich komme aus der Schweiz. Und du? - I come from Switzerland. And you?

* Können wir in deiner Mittagspauze kurz sprechen? - Can we talk briefly during your lunch break?

== Tag 30 November 2020

* Meinst du, ich soll wirklich bei diesem Unternehmen bewerben? - Do you think I should really apply to this company?

* Wie geht's dir heute? Schon etwas besser danke. - How are you today? Already a little better thanks.

* Geduld ist nicht unbedingt eine meiner Stärken - Patience is not necessarily one of my strengths.

* Ich vermisse dich! - I miss you

* Meine Mutter kocht immer etwas für mich, wenn ich aus der Schule komme.

* Marrie mag keinen Kaffee.

== Tag 28 November 2020

* Henriette liebt das Buch, das sie von ihrer Mutter geschenkt bekommen hat. - Henriette loves the book that her mother gave her.

* Sie liebt ihn gar nicht, sodern ist nur auf sein Geld aus! - She doesn't love him at all, but is only after his money!

* Ich bin am liebsten draußen, wenn die Sonne scheint. - I prefer to be outside when the sun is shining.

* Kannst du das bitte noch einmal widerholen? Er ist so laut hier. - Can you please repeat that again? He's so loud here.

* Ich kann es kaum erwarten, bald wieder zu Hause zu sein! - I can not wait, soon to be home again!

* Hast du schon die Rechnung bezahlt? - Have you paid the bill yet?


== Tag 27.11.2020

* Ich muss mich beeilen, weil ich heute pünktlich gehen will - I have to hurry because I want to leave on time today

* Ich gehe gerne zu Fuß - I like to walk

* Ich finde die Argumente des Politikers überzeugt - I find the politician's arguments convincing

* Im Schnitt mache ich zwei bis dreimal die Woche Sport. - On average, I do sport two to three times a week.

* Darfst du einfach so früh Feierabend machen? -  Can you just quit work so early?

* Jetzt hilf mir doch mal! - Now help me out!




* Marie mag keinen Kaffee.

* Das schaffe ich mit links - I can do that with my left hand

* Ich glaube, der Laden ist heute geschlossen - I think the store is closed today.

* Durch die Klimaerwärmung steht die Zukunft useres Planeten auf dem Spiel - The future of our planet is at stake due to global warning.
* Kannst du die Flasche auf den Tisch da vorne stellen - Can you put the bottle on the table over there

* Nächste Woche habe ich sehr viel zu tun. Deswegen kann ich noch nicht sagen, ob ich es schaffe, dich zu treffen. - I will be very busy next week. That is why I can not say wheather I will be able to meet you.

* Ich mag es gar nicht, wenn du traurig bist. - I do not like it when you are sad.

---------------------


